name: BungeecordServerLobby
main: xyz.Zeeraa.bungeecordserverlobby.BungeecordServerLobby
version: 1.0
author: Zeeraa
commands:
  reloadservers:
    description: reloads server list
    usage: /reloadservers
    aliases: [rsl, slrl, rlsl, serverlistreload]
  serverlist:
    description: shows the server list
    usage: /serverlist
    aliases: [sl, servers, menu, selector]